# Generated by Django 3.1 on 2020-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(max_length=20)),
                ('end_time', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
