# Generated by Django 3.1 on 2020-08-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_activityperiod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='ActivityPeriod',
        ),
    ]
