# Generated by Django 3.1 on 2020-08-20 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200819_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 20, 7, 47, 54, 913188, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 20, 7, 48, 30, 761865, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
